supabase.url=${SUPABASE_URL:https://jubpudczdaqfaszwhldy.supabase.co}
supabase.key=${SUPABASE_KEY:sb_publishable_BeOJxMDFGC3eDj_byVgJlQ_vizZtGm0}
supabase.jwt.secret=${7b7d84de-9231-4f38-8d59-38cb6f6fdf81}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

server.servlet.context-path=/api

logging.level.root=INFO
logging.level.com.example.api=DEBUG