supabase.url=${SUPABASE_URL:https://jubpudczdaqfaszwhldy.supabase.co}
supabase.key=${SUPABASE_KEY:sb_publishable_BeOJxMDFGC3eDj_byVgJlQ_vizZtGm0}
supabase.jwt.secret=${SUPABASE_JWT_SECRET}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

server.servlet.context-path=/api

logging.level.root=INFO
logging.level.com.example.api=DEBUG